---
title: "Analysis of Monthly Precipitation in Colorado"
author: "Christian Rohrbeck"
date: "26/03/2025"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the packages and data


```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(ggspatial)
library(patchwork)

ColoradoPrecip <- read.csv("PrecipitationColorado.csv")
ColoradoCities <- read.csv("Cities Colorado.csv")
```

## Check linearity

```{r, out.width='95%', fig.height=4, fig.width=12, fig.align='center'}
ggplot( ColoradoPrecip, aes( x=VALDEZ, y=WETMORE) ) + geom_point() + theme_bw() + 
ggplot( ColoradoPrecip, aes( x=TOWNER, y=STONINGTON) ) + geom_point() + theme_bw() + 
ggplot( ColoradoPrecip, aes( x=CARDIFF, y=NORTHGLENN) ) + geom_point() + theme_bw()
```

## Derive eigenvectors and eigenvalues

```{r}
head(ColoradoPrecip)
```

```{r}
Precip <- ColoradoPrecip %>% select( -date )
PCA <- prcomp( Precip, scale. = TRUE ) ## Combines all 3 steps
```

## Plot the ratio of eigenvalues

**Note:** prcomp() stores $\sqrt{\lambda_1},\ldots,\sqrt{\lambda_n}$:

```{r, fig.align='center', out.width='45%', fig.height=3.5, fig.width=5}
ColoradoEV <- data.frame( m=1:30, Ratio = cumsum(PCA$sdev^2) / sum(PCA$sdev^2) )
ggplot( ColoradoEV, aes(x=m, y=Ratio) ) + geom_point() + 
  geom_abline( intercept = 0.9, slope = 0, linewidth=1.5 ) + theme_bw() +
  ggtitle("Proportion of variance explained")
```

**What do we conclude?**

## Plot eigenvectors

We attach the eigenvectors to the spatial sites

```{r}
ColoradoCities <- ColoradoCities %>%
  mutate( PC1 = PCA$rotation[,1], PC2 = PCA$rotation[,2], PC3 = PCA$rotation[,3] ) %>%
  pivot_longer( cols=PC1:PC3, names_to="PC" )
```

Visualize the eigenvectors

```{r, fig.align='center', out.width='100%', fig.width=12, fig.height=4, message=FALSE}
ggplot( ColoradoCities, aes( x=LONG, y=LAT) ) + 
  facet_wrap( ~PC ) +
  annotation_map_tile() + 
  geom_spatial_point( aes(color=value), size=5 ) + 
  scale_color_distiller( palette="RdYlBu" ) +
  labs( x="Longitude", y="Latitude", color="value" )
```