---
title: "MA22019 2025 - Coursework 1"
format:
  pdf: default
  html:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Generative AI statement

*Please comment on your use of generative AI for this coursework.*



## Question 1

*Several areas of Utopia are historically suffering from poor air quality. The society "Clean Air for Utopia" has measured PM10 levels (in $\mu g/m^3$) at six sites across Utopia on a daily basis for several years. They now ask you to perform an analysis which explores how the six sites compare in terms of the recorded PM10 levels.*

*The society is further interested in identifying factors which may explain differences across the sites. They are aware that their current data does not allow them to make such conclusions. You are thus asked to suggest other data or information the society may want to collect so that they can address this question in the future.*

### Answer

*Please present your analysis for for Question 1 here.*

## Question 2a

*Which features regarding energy consumption and efficiency does the government of Utopia need to take into account when designing their new energy strategy?*

### Answer

*Please present your analysis for Question 2a here.*

## Question 2b

*Energy in Utopia is produced using four sources: several solar farms, wind farms, coal-fired power stations and a nuclear power station. Explore how much renewable energy sources, solar and wind, have been contributing to the energy production.*

*The current capacity for energy production using coal is 500,000 MWh per day. An advisor to the government of Utopia suggests to reduce this capacity by 40\% and to close the nuclear power station within the next two years. The latter is motivated by the country's difficulty to find a secure ultimate disposal place for the nuclear waste. What would be the impact of this plan on the country's capacity to meet its energy demand? Clearly state the assumptions underlying your approach.*

*Do you have any suggestions on how this plan may be improved? In your discussion, please take into account that Utopia is unable to import energy from abroad and to immediately build new solar and wind farms.*

### Answer

*Please present your analysis for for Question 2b here.*
