---
title: "Coursework 2 Data Preparation"
author: "Dr. Karim Anaya-Izquierdo"
date: "April 2025"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(tidytext)
library(sf)
library(stringr)
library(tidyr)
library(mvtnorm)
library(sp)
library(gstat)
library(lubridate)
```

## Question 1

### Create data set of fakes

```{r, warning=FALSE}
Fake1 <- readLines("original_data/downtrodden_poet.txt", encoding = "UTF-8")
Fake2 <- readLines("original_data/fallen_gentleman.txt", encoding = "UTF-8")
Fake3 <- readLines("original_data/misers_toll.txt", encoding = "UTF-8")
Fake4 <- readLines("original_data/orphans_heart.txt", encoding = "UTF-8")
Fake5 <- readLines("original_data/shopkeepers_lament.txt", encoding = "UTF-8")
```

```{r}
Fake1 <- data.frame( Title="The Downtrodden Poet", Text=Fake1 )
Fake2 <- data.frame( Title="The Fallen Gentleman", Text=Fake2 )
Fake3 <- data.frame( Title="The Miser’s Toll", Text=Fake3 )
Fake4 <- data.frame( Title="The Orphan’s Heart", Text=Fake4 )
Fake5 <- data.frame( Title="The Shopkeeper's Lament", Text=Fake5 )
Fakes <- rbind( Fake1, Fake2, Fake3, Fake4, Fake5 )
```

```{r}
write.csv( Fakes, "Dickens_Fakes.csv", row.names = FALSE, fileEncoding = "UTF-8" )
```

### Create data set of originals

```{r}
Dickens <- read.csv("Original Data/Dickens.csv", encoding = "UTF-8")
Dickens_chapters <- Dickens %>%
  group_by( title ) %>%
  mutate( chapter = cumsum( 
    str_detect( text, regex( "^chapter ", ignore_case = TRUE ) ) 
  ) )
```

```{r}
Dickens_chapters <- Dickens_chapters %>%
  filter( chapter > 0 ) %>%
  unite( col=document, title, chapter )
```

```{r}
set.seed(2025)
samp <- sample( unique(Dickens_chapters$document), size = 10, replace = FALSE )
```

```{r}
Dickens_originals <- Dickens_chapters %>%
  filter( document %in% samp ) %>%
  separate( document, c("Title", "Chapter"), sep="_", convert=TRUE ) %>%
  rename( Text = text)
```

```{r}
write.csv( Dickens_originals, "Dickens_Originals.csv", row.names = FALSE, 
           fileEncoding = "UTF-8" )
```


## Question 2

### Create shapefile and point locations

```{r}
UK <- read_sf("Original Data/UK Shapefile/UK_admin.shp")
```

```{r}
Somerset <- filter( UK, NAME_2 == "North Somerset")
Somerset <- Somerset %>% select( geometry )
```

```{r, fig.align='center', fig.width=4, fig.height=3, out.width='50%'}
set.seed(2025)
Somerset_coords <- st_coordinates(Somerset$geometry)
Somerset_coords[,1] <- 0.5 * Somerset_coords[,1] + 100
Somerset_coords[,2] <- 0.5 * Somerset_coords[,2] - 10
Shapefile <- st_sfc( st_polygon(list(Somerset_coords[,1:2]) ))
st_crs(Shapefile) <- 4326
write_sf( Shapefile, "Tesremos.shp")
Shapefile <- st_sfc( st_polygon(list(Somerset_coords[,1:2]) ))
```


```{r}
set.seed(2025)
margins <- st_bbox(Shapefile)
num_loc <- 200
coords <- cbind( runif( num_loc, margins[1], margins[3] ),
                 runif( num_loc, margins[2], margins[4] ) )
coords <- st_sfc( st_multipoint( coords ) ) %>% st_cast( "POINT" )
```

```{r}
ind <- st_intersects(coords, Shapefile)
ind <- which( as.vector(ind)[1:200] == 1 )
coords <- coords[ind,]
```

```{r}
Locations           <- data.frame( ID=1:length(coords) )
temp                <- st_coordinates( coords )
Locations$Longitude <- round(temp[,1],5)
Locations$Latitude  <- round(temp[,2],5)
Locations <- Locations %>% 
  arrange( Longitude )
for( i in 1:nrow(Locations) )
  Locations$ID[i] <- paste("Site_",i,sep="")
write.csv( Locations, "Tesremos_Locations.csv", row.names = FALSE )
```


### Create observations for March

```{r}
set.seed(850)
Water <- Locations %>% select( Longitude, Latitude )
Distance <- as.matrix( dist(Water, upper = TRUE, diag = TRUE ) )
Sigma <- 7 * exp( -15*Distance )
Z <- rmvnorm( 1, mean = rep(-20,length(Water$Longitude)), sigma=Sigma )
Water$Anomaly <- Z[1,]
```

```{r}
set.seed(2000)
Sigma <- 0.2 * exp( -9*Distance )
Z <- rmvnorm(31, mean = rep(0,nrow(Water)), sigma=Sigma )

Water_March <- matrix( 0, 31, nrow(Water) )
for( i in 1:31 )
  Water_March[i,] <- Water$Anomaly + Z[i,]
```

```{r}
Water_March <- as.data.frame(round(Water_March,2))
for( i in 1:nrow(Locations) )
  names(Water_March)[i] <- paste("Site_",i,sep="")
Water_March <- Water_March %>%
  mutate( Date = as_date("01/03/2024", format="%d/%m/%Y") + 0:30 ) %>%
  relocate(Date, .before=Site_1 )
```

### Create observations for August

```{r}
Water <- Locations %>% 
  select( Longitude, Latitude ) %>%
  mutate( Longitude = min(Longitude) + 5 * 
            ( Longitude-min(Longitude) > 0.09 ) *
            ( Longitude - min(Longitude) ) )
Distance <- as.matrix( dist(Water, upper = TRUE, diag = TRUE ) )

set.seed(1000)
Sigma <- 9 * exp( -9*Distance )
Z <- rmvnorm(1, mean = rep(-25,nrow(Water)), sigma=Sigma )
```

```{r}
Water <- Water %>% 
  mutate( Longitude = Locations$Longitude, Anomaly=Z[1,] )
```


```{r}
set.seed(3000)
Sigma <- 0.2 * exp( -9*Distance )
Z <- rmvnorm(31, mean = rep(0,nrow(Water)), sigma=Sigma )

Water_August <- matrix( 0, 31, nrow(Water) )
for( i in 1:31 )
  Water_August[i,] <- Water$Anomaly + Z[i,]
```

```{r}
Water_August <- as.data.frame(round(Water_August,2))
for( i in 1:nrow(Locations) )
  names(Water_August)[i] <- paste("Site_",i,sep="")
Water_August <- Water_August %>%
  mutate( Date = as_date("01/08/2024", format="%d/%m/%Y") + 0:30 ) %>%
  relocate(Date, .before=Site_1 )
Water <- bind_rows( Water_March, Water_August)
write.csv(Water, "Tesremos_Water.csv", row.names = FALSE )
```


## Question 3

## Create the "Isles of Sofara"


```{r}
ROM <- read_sf( "Original Data/Romania Shapefile/gadm41_ROU_1.shp" )
```

```{r}
set.seed(20000)
Islands <- ROM[sample(1:42,5),] %>% select( NAME_1, geometry )
Islands$NAME_1   <- c( "Paxora", "Solvenya", "Justitia", "Calmorra", "Ecliptria" )
Islands$geometry <- st_geometry(Islands) + c(-50,-30)
st_crs(Islands)  <- 4326
Islands          <- Islands %>% 
  st_simplify( dTolerance = 100) %>%
  rename( Name=NAME_1 )
```

```{r, fig.align='center', fig.width=4, fig.height=3, out.width='50%', message=FALSE, warning=FALSE}
Islands_centroids <- st_centroid(Islands)
ggplot(Islands) + geom_sf() + theme_bw() + 
  geom_sf_text( data=Islands_centroids, aes(label = Name), color="darkblue" ) + 
  labs( x="Longitude", y="Latitude" )
```

```{r}
write_sf( Islands, "Isles_of_Sofara_Shapefile/Isles_of_Sofara.shp" )
```


## Import messages

```{r}
set.seed(2025)
Distress <- read.csv("Original Data/DistressMessages.csv", encoding = "UTF-8", header = TRUE) %>%
  rename( Message = Distress.Message) %>%
  mutate( Message = paste("#IoSTSHelp", Message, sep=" ") )
Reports <- read.csv("Original Data/StormMessages.csv", encoding = "UTF-8", header=TRUE) %>%
  rename( Message = Storm.Message)
Messages <- bind_rows( Distress, Reports )
Messages <- Messages[sample(1:nrow(Messages)),]
```



## Simulate locations of disasters

```{r}
Messages <- data.frame( Message = Messages )
Island_names <- c( "Paxora", "Solvenya", "Justitia", "Calmorra", "Ecliptria" )
Messages <- Messages %>%
  mutate( Longitude = rep(0,nrow(Messages)),
          Latitude = rep(0,nrow(Messages)),
          Island = rep("Paxora", nrow(Messages) ) )


set.seed(4000)
centres <- st_coordinates(Islands_centroids)
k <- 1

while( k <= nrow(Messages) ){
  centre_i <- centres[sample(1:5,1),]
  centre_i <- centre_i + rnorm(2,0,0.3)
  num_messages <- rgeom( 1, 0.02 )
  for( j in 1:num_messages ){
    if( k>nrow(Messages) )
      next;
    Messages$Longitude[k] <- round( runif(1, centre_i[1]-0.5, centre_i[1]+0.5), 4)
    Messages$Latitude[k]  <- round( runif(1, centre_i[2]-0.5, centre_i[2]+0.5), 4 ) 
    loc_sfc <- st_sfc( st_point( c(Messages$Longitude[k], Messages$Latitude[k]) ) )
    st_crs(loc_sfc)  <- 4326
    if( !is.na( st_intersects(loc_sfc, Islands)[1] > 0 ) ){
      Messages$Island[k] <- Island_names[st_intersects(loc_sfc, Islands)[1][[1]]]
      if( rbinom( 1,1,0.05) == 1 ){
        Messages$Longitude[k] <- NA
        Messages$Latitude[k]  <- NA 
      }
      k <- k+1
    }
  }
}
    
```


```{r}
write.csv( Messages, "Isles_of_Sofara_Messages.csv", row.names = FALSE )
```
