---
title: "Analysis of NRFA Data"
date: "05/02/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data and R packages 

```{r, warning=FALSE, message=FALSE}
library( lubridate )
library( dplyr )
```

```{r}
Bathford_RF <- read.csv( "Bathford River Flow.csv", skip=20, header=FALSE,
                         colClasses = c("character","numeric","NULL") ) 
```

## Data Cleaning

Check which variables need to converted and renamed

```{r}
glimpse( Bathford_RF )
```

### Change variables names

```{r}
Bathford_RF <- rename( Bathford_RF, Date = V1, RiverFlow = V2 )
```

### Convert to correct type

```{r}
Bathford_RF$Date <- as_date( Bathford_RF$Date, format="%Y-%m-%d" )
```


## Data Wrangling and visualization

### Proportion of missing data

```{r}
mean( is.na( Bathford_RF$RiverFlow ) )
```

### Plot river flow over time

```{r, out.width='60%', fig.height=4, fig.width=6, fig.align='center'}
plot( Bathford_RF$Date, Bathford_RF$RiverFlow, type='l',
      xlab="Date", ylab="River Flow", cex.lab = 1.5 )
```

### Filter observations based on date and observed river flow

```{r}
Bathford_RF_High <- filter( Bathford_RF, RiverFlow > 100 )
slice_head( Bathford_RF_High, n=5 )
```

```{r}
Bathford_RF_High <- filter( Bathford_RF, RiverFlow > 100, year(Date) > 1990 )
slice_head( Bathford_RF_High, n=5 )
```
