---
title: "Analysis of wind in Bela Vista"
author: "Christian Rohrbeck"
date: "19/02/2025"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(patchwork)
```

## Loading the data

```{r}
wind_BV <- read.csv("wind_bela_vista.csv")
```

```{r}
glimpse(wind_BV)
```

## Histogram for wind direction

```{r, fig.height=4, fig.width=9, out.width='80%', fig.align='center'}
Plot_Cartesian <- ggplot(wind_BV, aes(x = Wind.Direction)) +
    geom_histogram(bins = 120) +
    labs(x = "Wind Direction")

Plot_Polar <- Plot_Cartesian + coord_polar()

Plot_Cartesian + Plot_Polar
```

```{r}
Plot_Cartesian
```

## Relation between wind speed and direction

```{r, fig.height=4, fig.width=9, out.width='80%', fig.align='center'}
Plot_Cartesian <-
    ggplot(wind_BV, aes(x = Wind.Direction, y = Gust.Speed)) +
    geom_point() +
    geom_smooth() +
    labs(x = "Wind Direction", y = "Wind gust speed in m/s")

Plot_Polar <- Plot_Cartesian + coord_polar(theta = "x")

Plot_Cartesian + Plot_Polar
```


## Producing pie charts in R 

```{r, out.width='90%', fig.align='center', fig.height=4, fig.width=9}
df <- data.frame("prob" = c(0.3, 0.4, 0.3), "group" = c("A", "B", "C"))

Barplot <- ggplot(df, aes(x = "", y = prob, fill = group)) +
    geom_col() +
    labs(x = "", y = "")

PieChart <- Barplot + coord_polar(theta = "y")

Barplot + PieChart
```
