---
title: "Switching Data Formats Example"
author: "Christian Rohrbeck"
date: "19/02/2025"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(dplyr)
```


## Load the data

```{r}
Manaus <- read.csv("manaus_temperature.csv" )
```

## Case 1 - Comparison months

### Data Cleaning

```{r}
Manaus <- Manaus %>% 
  mutate( JAN = na_if( JAN, 999.9 ), FEB = na_if( FEB, 999.9 ) )
```

### Plotting the data

```{r, out.width='50%', fig.align='center'}
Manaus %>% 
  filter( JAN < 100, FEB < 100 ) %>%
  ggplot( aes(x=JAN, y=FEB) ) + geom_point() + 
  labs(x="Temperature in January", y="Temperature in February") + 
  theme_bw() +
  theme( axis.title=element_text(size=16), 
         axis.text=element_text(size=14) )
```

## Case 2 - Analyse change over time

### Changing the data structure

The data format is not good for creating a line plot of temperature over time. Sow e have to change the format:

```{r}
library(tidyr)
Manaus_long <- Manaus %>%
  pivot_longer(cols = JAN:DEC, names_to = "Month" )
```

```{r}
glimpse(Manaus_long)
```

To reverse the process and convert the longer to the wider format, we use pivot_wider():

```{r}
Manaus_short <- Manaus_long %>%
  pivot_wider( names_from = Month, values_from = value)
```

### Plotting the data


```{r}
## Convert abbreviation for month into number
Manaus_long <- 
  Manaus_long %>% 
  mutate( Month = case_when( 
    Month == "JAN" ~ "01", Month == "FEB" ~ "02", Month == "MAR" ~ "03", 
    Month == "APR" ~ "04", Month == "MAY" ~ "05", Month == "JUN" ~ "06",
    Month == "JUL" ~ "07", Month == "AUG" ~ "08", Month == "SEP" ~ "09", 
    Month == "OCT" ~ "10", Month == "NOV" ~ "11", Month == "DEC" ~ "12"
    ) 
  )

## Combine year and month and convert to date
Manaus_long <- Manaus_long %>%
  mutate( Date = paste( Manaus_long$YEAR, Manaus_long$Month, sep="-" ) ) %>%
  mutate( Date = ym( Date ) )
```

```{r, warning=FALSE, fig.align='center', out.width='55%', fig.cap="Average monthly temperature for Manaus, Brazil, between 1910 and 2019."}
Manaus_long %>%
  mutate( value = na_if( value, 999.9 ) ) %>%
  ggplot( aes("x"=Date, "y"=value) ) + 
  geom_line() + geom_smooth() +
  labs( y="Average Monthly Temperature") + theme_bw() +
  theme( axis.title=element_text(size=16), axis.text=element_text(size=14) )
```
