---
title: "Visualizing population density across London boroughs"
author: "Christian Rohrbeck"
date: "02/04/2025"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the data and shapefile

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(sf)

London <- read_sf("London.shp")
```

```{r}
names(London)
```

## Explroe the data structure

The following illustrates that the shapefile comes with a data frame

```{r}
class( London )
```

## Load and clean the population data

```{r}
London_population <- read.csv( "London.csv" )
London_population <- London_population %>% 
  mutate( Population = as.numeric( gsub("\\,","",Population) ) )
```

## Merge data sets and calculate density

```{r}
London <- inner_join( x=London, y=London_population, by=c("NAME"="Borough") )
London <- London %>% mutate( Density = Population / HECTARES )
```


## Visualzation 1: Colour as visual cue

```{r, message=FALSE, fig.align='center', out.width='50%'}
ggplot( data=London, aes(fill=Density) ) + geom_sf() + theme_bw() +
  scale_fill_distiller( palette="Reds", trans="reverse" ) + 
  theme( axis.title=element_text(size=15), axis.text=element_text(size=15) ) + 
  labs( x="Longitude", y="Latitude" )
```

## Visualzation 2: Size of points as visual cue

```{r, message=FALSE, fig.align='center', out.width='50%', }
ggplot( data=London ) + geom_sf() + theme_bw() + 
  geom_point( data=st_centroid(London), aes( size = Density, geometry = geometry), 
              stat = "sf_coordinates" ) +
  labs( x="Longitude", y="Latitude" ) + 
  theme( axis.title=element_text(size=15), axis.text=element_text(size=15) )
```
