install.packages("rmarkdown")
install.packages("dplyr")
install.packages("lubridate")
install.packages("ggplot2")
install.packages("RColorBrewer")
install.packages("patchwork")
install.packages("tidyr")
install.packages("tidytext", dependencies = TRUE)
install.packages("wordcloud")
install.packages("sf")
install.packages("ggspatial")
install.packages("prettymapr")
install.packages("sp")
install.packages("gstat")
install.packages("spatstat")
install.packages("raster")